#pragma once
#include "CoreMinimal.h"
#include "EActivityAnimationType.generated.h"

UENUM(BlueprintType)
enum class EActivityAnimationType : uint8 {
    NONE,
    SWAP,
    RELOAD,
    SHOTGUN_BLAST,
    FLAME_THROWER_BLAST,
    GRENADE_LAUNCH,
    SEARCH,
    SEARCH_CORPSE,
    SEARCH_HIGH,
    KEYBOARD,
    DATAPAD,
    WELDING,
    UNWELDING,
    HEAL_HIMSELF,
    HEAL_PARTNER,
    TAKE_STRESSPILLS,
    TAKE_PAINKILLER,
    REPRIMANDE,
    CALM_DOWN,
    DROP_MINES,
    SENTRY_DROP,
    SENTRY_REPAIR,
    SENTRY_RELOAD,
    DEMOLITION,
    DEPLOY_MOTION_TRACKER,
    STRUGGLE,
    OPEN_COCOON,
    RALLY_DESERTER,
    CARRY_TAKE,
    CARRY_DROP,
    APC_ENTER,
    POWERLOADER_ENTER,
    POWERLOADER_LEAVE,
    POWERCORE_EXTRACTION,
    FACEHUGGER_INJECTION,
};

