#pragma once
#include "CoreMinimal.h"
#include "EOtagoEventEffectType.generated.h"

UENUM(BlueprintType)
enum class EOtagoEventEffectType : uint8 {
    NO_EFFECT,
    FORCE_NEXT_EVENT,
    LOSE_DEPLOYMENT,
    EARN_ENGINEER,
    LOSE_ENGINEER,
    SPEND_ENGINEER,
    EARN_PHYSICIAN,
    LOSE_PHYSICIAN,
    SPEND_PHYSICIAN,
    EARN_MARINE,
    LOSE_MARINE,
    EARN_RANDOM_SURVIVOR,
    EARN_MATERIALS,
    LOSE_MATERIALS,
    EARN_XENO_SAMPLES,
    LOSE_XENO_SAMPLES,
    EARN_XP,
    SUFFER_TIREDNESS,
    CURE_TIREDNESS,
    SUFFER_EXHAUSTION,
    CURE_EXHAUSTION,
    CURE_TIREDNESS_AND_EXHAUSTION,
    SUFFER_TRAUMA,
    CURE_TRAUMA,
    SUFFER_MEDBAY_CARE,
    DECREASE_INFESTATION,
    INCREASE_INFESTATION,
    DECREASE_DEATHCLOCK,
    INCREASE_DEATHCLOCK,
    DISABLE_MEDBAY_PASSIVE_CARE,
    DISABLE_LAB_RESEARCH,
    ADD_LOOT_MISSION,
    ADD_KILL_MISSION,
};

